version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: discord-bot-postgres
    environment:
      POSTGRES_USER: discordbot
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: discordbotdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - discord-bot-network

volumes:
  postgres_data:

networks:
  discord-bot-network:
