name: Deploy Bot to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IP: ${{ secrets.IP_VPS }}
      PORT: ${{ secrets.PORT_VPS }}
      LOGIN: ${{ secrets.LOGIN_VPS }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.IP }}
          username: ${{ env.LOGIN }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ env.PORT }}
          script: |
            # Définir le chemin du projet sur le VPS
            PROJECT_PATH="xxxTentacion"

            # Vérifier si le projet existe déjà
            if [ -d "$PROJECT_PATH" ]; then
              echo "Le projet existe déjà. Mise à jour du code..."
              cd $PROJECT_PATH
              git pull origin main
            else
              echo "Le projet n'existe pas. Clonage du dépôt..."
              git clone https://github.com/your-username/your-repo.git $PROJECT_PATH
              cd $PROJECT_PATH
            fi

            # Construire et démarrer les conteneurs Docker
            docker-compose down
            docker-compose up -d --build
