name: Deploy Bot to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IP: ${{ secrets.IP_VPS }}
      PORT: ${{ secrets.PORT_VPS }}
      LOGIN: ${{ secrets.LOGIN_VPS }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.IP }}
          username: ${{ env.LOGIN }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ env.PORT }}
          script: |
            # Définir le chemin du projet sur le VPS
            PROJECT_PATH="/home/anthony/xxxtentacion"
            cd $PROJECT_PATH
            #sudo git pull origin master on tape le mot de passe dans secret.password
            echo ${{ secrets.PASSWORD }} | sudo -S git pull origin master
            # Installer les dépendances Node.js
            sudo npm install

            # Compiler le TypeScript en JavaScript
            sudo npm run build

            # Lancer l'application Node.js en arrière-plan
            pm2 stop index || true # Arrêter l'application si elle est déjà en cours d'exécution
            pm2 start dist/index.js --name xxxtentacion # Démarrer l'application avec pm2

      - name: Verify Deployment
        run: echo "Deployment successful."
