name: Deploy Bot to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IP: ${{ secrets.IP_VPS }}
      PORT: ${{ secrets.PORT_VPS }}
      LOGIN: ${{ secrets.LOGIN_VPS }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.IP }}
          username: ${{ env.LOGIN }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ env.PORT }}
          script: |
            # Définir le chemin du projet sur le VPS
            PROJECT_PATH="xxxtentacion"

            # Vérifier si le projet existe déjà
            if [ -d "$PROJECT_PATH" ]; then
              echo "Le projet existe déjà. Mise à jour du code..."
              cd $PROJECT_PATH
              git pull origin main
            else
              echo "Le projet n'existe pas. Clonage du dépôt..."
              git clone https://github.com/Anthonydt16/xxxtentacion.git
              cd $PROJECT_PATH
            fi

            # Créer ou mettre à jour le fichier .env
            if [ -f .env ]; then
                echo "Fichier .env trouvé. Mise à jour des variables..."
            else
                echo "Fichier .env non trouvé. Création d'un nouveau fichier .env..."
                touch .env
            fi
            sed -i 's/^\(TOKEN\s*=\s*\).*$/\1${{ secrets.TOKEN }}/; s/^\(CHANNEL_ID\s*=\s*\).*$/\1${{ secrets.CHANNEL_ID }}/; s/^\(SPOTIFY_CLIENT_ID\s*=\s*\).*$/\1${{ secrets.SPOTIFY_CLIENT_ID }}/; s/^\(SPOTIFY_CLIENT_SECRET\s*=\s*\).*$/\1${{ secrets.SPOTIFY_CLIENT_SECRET }}/; s/^\(GUILD_ID\s*=\s*\).*$/\1${{ secrets.GUILD_ID }}/;' .env

            # Installer les dépendances Node.js
            npm install

            # Compiler le TypeScript en JavaScript
            npm run build

            # Lancer l'application Node.js en arrière-plan
            pm2 stop index || true # Arrêter l'application si elle est déjà en cours d'exécution
            pm2 start dist/index.js --name xxxtentacion # Démarrer l'application avec pm2

      - name: Verify Deployment
        run: echo "Deployment successful."
